BUFFER_SIZE: 500
BATCH_SIZE: 4
INPUT_WIDTH: 64
INPUT_HEIGHT: 64


S1_INPUT_CHANNELS: 4
S2_INPUT_CHANNELS: 13
NUM_TIMESTEPS: 16
NUM_CLASSES: 10 # num_crops + 1
EPOCHS: 1


TRAIN_PATH: '../../data/tfrecords/ca_central_valley_cropland/crop_class_train_s1-t_s2-lulc_ntiles_160_split_64px_nimgs_1817.tfrecords'
TEST_PATH: '../../data/tfrecords/ca_central_valley_cropland/crop_class_test_s1-t_s2-lulc_ntiles_41_split_64px_nimgs_454.tfrecords'

MAIN_DIR: "../../models/class_models/"
LOG_DIR: "../../models/class_models/logs/"
CHECKPOINT_DIR: "../../models/class_models/training_checkpoints"
CHECKPOINT_FOLDER: "crop_class_final_s1_and_s2_networks"
IMAGE_DIR: '../../class_models/figures/'
NORMALIZATION_DIR: '../../models/class_models/band_normalization_calculations'
TIMESERIES_PRED_REGION: 'ca_central_valley_cropland'

RANDOM_SEED: 7
CALCULATE_NORMALIZATION: False
IMGS_FOR_NORMALIZATION: 2000

NUM_CROPS: 10
SAVE_CROP_CT_CSV: True
LOAD_EXISTING: False

COMBINED_MODEL: True

# Model run configurations
TRAIN: True
CALC_DS_STATS: False
LOG: True
CALCULATE_LC_STATS: False
PLOT_TS_PREDICTIONS: False
SAVE_MODEL: False
PLOT_CROP_PREDS: False